### ISSUE TITLE
How to integrate OS-Copilot with Friday-front.

### ISSUE THREAD

**Issue by powerstar0926** [OS-Copilot/OS-Copilot#26]
**Describe the bug**

I want to integrate OS-Copilot with Friday-front.
I followed instructions but I couldn't integrate.
OS-Copilot works well with terminal. 
How to solve this problem?

**Comment by heroding77** [comment]
I'm sorry, due to recent optimizations and adjustments to the code of OS-Copilot, the latest version no longer supports Friday-front. Please run OS-Copilot directly through the terminal. We are currently focused on improving the smoothness of terminal usage to enhance user experience. Stay tuned for updates!
