### ISSUE TITLE
Lots of mistakes 

### ISSUE THREAD

**Issue by gitizenss** [OS-Copilot/OS-Copilot#8]
Doesnt seem to have capability to autonomously learn or even check if it failed or succeeded.

I must have done something wrong, because compared to the paper this seems not as capable as autogpt.

Does not seem to have any memory of any previous messages as well

Have not been able to get it to do anything without fails, fresh install.

![VirtualBoxVM_arCZsaEAeS](https://github.com/OS-Copilot/FRIDAY/assets/44759128/8fb52360-1c0b-424c-bb73-3d4c83553a68)
![VirtualBoxVM_kuqlWGmRof](https://github.com/OS-Copilot/FRIDAY/assets/44759128/d0f795ea-b2c4-4518-9367-c3f5a03f5851)
![VirtualBoxVM_s2IzbiinxI](https://github.com/OS-Copilot/FRIDAY/assets/44759128/d1679c9d-9ec5-473e-88f6-19086e099684)
![VirtualBoxVM_A0ykxQw4Og](https://github.com/OS-Copilot/FRIDAY/assets/44759128/db20372e-21ba-46a5-84b1-813eb7a5f50d)

**Comment by gitizenss** [comment]
Also does not attempt to save skills, and has a lot of the classic issues like leaving out methods when generating code causing failures, or assuming that it can't interact with filesystem.

Am I doing something wrong? I've tried switching out multiple GPT 4 version, installing all Gismos, etc. Would really love to use this for something without it breaking

![VirtualBoxVM_fEYM1LswXa](https://github.com/OS-Copilot/FRIDAY/assets/44759128/853b1016-a0a8-4876-ae77-9f6846ec508e)

**Comment by hccngu** [comment]
Hi~ gitizens,
Thank you for using FRIDAY~
Currently, FRIDAY only supports single-turn conversations, and all API tools need to be configured before use.
If you need to view the list of existing tools, perhaps asking it to 'list all files in `friday/action_lib/code`' would be more effective.
If the corresponding tool is not stored after performing a task, you can try reducing the `--score` in `run.py`.

**Comment by gitizenss** [comment]
I'm very confused, because it seems like it has NO memory capability OR ability to learn. I have provided about 30 different tasks to it, and action_lib/code does not change. 

I have been reading everything I can, trying to find how to make it actually try to save any information / learn, for hours. I still cannot use it for anything more than zipping files or downloading from web. 

Insight into how it can self-improve would be very appreciated. I follow instructions but the result is a tool that does not work.

**Comment by gitizenss** [comment]
![VirtualBoxVM_RnxxHhYJld](https://github.com/OS-Copilot/FRIDAY/assets/44759128/61fa8b59-ef10-4337-8758-3eb7d859254d)
![VirtualBoxVM_fyH9PyM20i](https://github.com/OS-Copilot/FRIDAY/assets/44759128/96454b6b-f9b6-4343-aacf-205232e26e05)
Here I tried to instruct it to learn how to run commands without using subprocess since it was not able to read outputs. Even after this, it immediately tries to use subprocess to run a command.

Is this what the tool is like for everyone else? Is anyone not experiencing this?

**Comment by heroding77** [comment]
Hi, gitizenss,
We are delighted that you have conducted such extensive exploration of FRIDAY, I will answer each of your questions one by one~

1. When designing, we aim to preserve tools of high quality and versatility as much as possible. Therefore, we only retain tools that score 8 or above. If you want to store as many coding tools as possible, you can try reducing the `--score` in `run.py`, 5 or 6 is a suitable choice.

2. Our current unified interaction interface with the operating system is implemented through subprocess, so bypassing subprocess is not possible. 

3. For the sake of safety, FRIDAY requires that all file operations must be performed in the `working_dir` folder. If you wish to perform special file operations, please try to place the files in this directory. Otherwise, you will need to provide the detailed path of the file in the task description to avoid errors.

Furthermore, when assisting the model with self-improvement, you can make the task description as detailed as possible. This can prevent ambiguity during the model's planning phase and also help you create higher quality tools.

I hope the above responses can solve the problems you encountered and help you better understand FRIDAY's working process and self-improvement.

**Comment by gitizenss** [comment]
#3 was never an issue

I think this would be **much** easier to figure out if an example folder existed, or a seperate branch containing the files that were used in the video recording demos on the github.io page. 

Right now it is so difficult to begin working with it for anything due to this. The tool lacks any reference examples of utilization, making it very difficult to figure out what it's capable of. 

From my POV, I am directly telling it to create & save a skill for a very specific task, and it consistently fails to do this, so I really have no idea how the demo videos were achieved.

**Comment by hccngu** [comment]
We have updated the code, and the structure of the code released this time is clearer and more convenient to use. Please try it again, and if you have any problems, feel free to contact us~
